[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true # allow foundry to run commands / scripts directly on my machine NOTE: try to keep it to false as long as possible (security)

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
